### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/Gymnasium#12]
This is a loose roadmap of our plans for major changes to Gymnasium:

December:
- [x] Experimental new wrappers
- [x] Experimental functional API
- [x] Python 3.11 support

February / March:
- [x] Official Conda packaging
- [x] Add Experimental vector API
- [x] Add full testing for experimental wrappers
- [ ] Add Experimental vector wrappers 
- [x] Add initial support for Minari 
- [x] Release v0.28.0

April:
- [ ] Fix all bugs and update documentation for experimental features
- [ ] Add functional versions of all gymnasium environments
- [ ] Make initial release of Brax environments 
- [ ] Extensive envpool integration for creating vectorized environments
- [ ] Release v0.29.0 as an intermediate version with experimental functional, new wrappers and vectors to root

May:
- [ ] Release v0.30.0 with old wrapper and vector removed

June:
- [ ] Move Box2D and MuJoCo environments to separate repos for reproducibility
- [ ] 1.0 release

**Comment by Syzygianinfern0** [comment]
How can new contributors get involved?

**Comment by pseudo-rnd-thoughts** [comment]
Could you join our discord server https://discord.gg/bnJ6kubTg6 and put a message in the new contributes channel with any particular topics that you would like to work on

**Comment by kir0ul** [comment]
I'd be interested to have a `Gymnasium.jl` Julia wrapper, happy to help in any way if that's in scope! :slightly_smiling_face:

**Comment by jkterry1** [comment]
We're planning to worry about multi-language support in the future after some of the current items are ironed

**Comment by juhannc** [comment]
I didn't want to open an extra issue for that, but regarding the full type hint support in the future, it should be considered to switch to [numpys typing module](https://numpy.org/devdocs/reference/typing.html).

**Comment by pseudo-rnd-thoughts** [comment]
@juhannc Thanks for the suggestion, we are already in the process of adding this in https://github.com/Farama-Foundation/Gymnasium/pull/37
If you have experience with using numpy typing, I would be open to you review the PR and any suggestions for improving it

**Comment by mkschleg** [comment]
Not to clutter this thread, but @kir0ul I needed a julia wrapper for my research as well. Just made an unofficial minimal wrapper around the Gymnasium python interface here: https://github.com/mkschleg/Gymnasium.jl. Pretty under-tested and no guarantees, but a starting point. It isn't (and probably won't be depending on the makers of gymnasium's plans) registered. 

The makers of gymnasium for python can fork this in their own repo for official registration if they want.

**Comment by Kenshiro-28** [comment]
Hi! Will you add support for Gym Retro? :)

**Comment by pseudo-rnd-thoughts** [comment]
Hi, I believe that the retro is being maintained - https://github.com/MatPoliquin/stable-retro

**Comment by Kenshiro-28** [comment]
> Hi, I believe that the retro is being maintained - https://github.com/MatPoliquin/stable-retro

Thank you! :)  

It looks a personal project, is it monitored from some team related with OpenAI or Farama Foundation?

**Comment by Kallinteris-Andreas** [comment]
Closing, since 1.0 is released
